CC: gcc -Wall

all:
	$(CC) -o main main.c
	$(CC) -o main2 main2.c
	$(CC) -o main3 main3.c -lrt
	$(CC) -o main4 main4.c
	$(CC) -o main5 main5.c -pthread -lrt
	$(CC) -o main6 main6.c -pthread -lrt
	rm -rf

