CC: gcc -Wall

all:

	$(CC) -o main main.c -pthread -lm
	rm -rf

test:
	./main 1 ./mona_lisa.ascii.pgm ./filter.txt ./result.ascii.pgm

test2:
	./main 2 ./mona_lisa.ascii.pgm ./filter.txt ./result.ascii.pgm

test3:
	./main 4 ./mona_lisa.ascii.pgm ./filter.txt ./result.ascii.pgm

test4:
	./main 8 ./mona_lisa.ascii.pgm ./filter.txt ./result.ascii.pgm

test5:
	./main 1 ./mona_lisa.ascii.pgm ./filter2.txt ./result.ascii.pgm

test6:
	./main 2 ./mona_lisa.ascii.pgm ./filter2.txt ./result.ascii.pgm

test7:
	./main 4 ./mona_lisa.ascii.pgm ./filter2.txt ./result.ascii.pgm

test8:
	./main 8 ./mona_lisa.ascii.pgm ./filter2.txt ./result.ascii.pgm

test9:
	./main 1 ./mona_lisa.ascii.pgm ./filter3.txt ./result.ascii.pgm

test10:
	./main 2 ./mona_lisa.ascii.pgm ./filter3.txt ./result.ascii.pgm

test11:
	./main 4 ./mona_lisa.ascii.pgm ./filter3.txt ./result.ascii.pgm

test12:
	./main 8 ./mona_lisa.ascii.pgm ./filter3.txt ./result.ascii.pgm